# syntax=docker/dockerfile:1

FROM cameronmcnz/ant-jdk8-git:latest

# build extdoc
WORKDIR /extdoc
COPY ./extdoc /extdoc
# compiles and builds to "/extdoc/build/dist/ext-doc-snapshot"
RUN ant clean compile jar dist

# build extjs 2.0.2 documentation
# they say "source" in the README, but it's actually pointing to "src"
COPY ./build/source /extdoc/build/dist/ext-doc-snapshot/sample/ext/src
WORKDIR /extdoc/build/dist/ext-doc-snapshot
# remove the sample.js file there to get rid of the sample classes they included
RUN rm ./sample/sample.js && java -jar ./ext-doc.jar -p ./sample/ext.xml -o /docs -t ./template/ext/template.xml -verbose
