name: CI

on:
  push:
    branches: [ "main" ]
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Run a one-line script
        run: ./build.sh "latest"

      - name: Release
        uses: fnkr/github-action-ghr@v1
        env:
          GHR_PATH: ./build/horizonjs-latest.zip
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
